/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.*;

public class DeckTest {
    @Test(timeout = 20000)
    public void testDeckFiftyTwoDiffVal() {
    	DeckOfCards deck = new DeckOfCards();
    	checkDeck(deck);
    	testShuffle(deck);
    }

    void testShuffle(DeckOfCards d){
    	d.shuffle();
    	checkDeck(d);
    }

    private void checkDeck(DeckOfCards deck){
    	Set<Card> cs = new HashSet<>();
    	Card c = deck.dealOneCard();  //dealFirstCard
    	int i=1;
    	while (c != null){          //deal until null return
    		assertTrue(cs.add(c));  //add to hashset
    		c = deck.dealOneCard(); //deal another card
    	}
    	assertEquals(cs.size(),52);  //check if got 52 different card in set when deck is empty
    }
}
